### ISSUE TITLE
CUDA kernel failed : an illegal memory access was encountered 

### ISSUE THREAD

**Issue by robot0321** [tatsy/mcubes_pytorch#1]
I ran your example code and got an error msg.
(I made .so file with setup.py and added library path.)

> CUDA kernel failed : an illegal memory access was encountered                                             > std::vector<at::Tensor> mcubes_cuda(at::Tensor, float) at L:583 in /home/chung/workspace/mcubes_pytorch/cxx/mcubes_cuda.cu

The problem arises at `marching_cubes()` function

My env is ubuntu 20.04 and CUDA 11.0, Driver version 450.102.04

**Comment by tatsy** [comment]
What version of PyTorch and Python are you using?

**Comment by robot0321** [comment]
Pytorch 1.7.1

The problem was due to the number N... I used 256 and it corrupted.
Thanks for your fast answer ;)

**Comment by tatsy** [comment]
Great! As you noticed, the number `N` would be a problem if you are using a GPU with small memory resource.

Thank you for your information.
